"""
digest.py
---------
Formats summarized articles into a clean daily digest
and saves it to the output/ folder.
"""

import os
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


def format_digest(articles: list[dict], category: str = "technology") -> str:
    """
    Format a list of summarized articles into a readable digest.

    Args:
        articles: List of article dicts with summary key
        category: News category label

    Returns:
        Formatted digest string
    """
    date_str = datetime.now().strftime("%B %d, %Y")
    time_str = datetime.now().strftime("%H:%M")

    lines = []
    lines.append("=" * 60)
    lines.append(f"  📰 Daily News Digest — {category.upper()}")
    lines.append(f"  📅 {date_str} at {time_str}")
    lines.append("=" * 60)
    lines.append("")

    for i, article in enumerate(articles, 1):
        lines.append(f"{i}. {article['title']}")
        lines.append(f"   Source: {article['source']}")
        lines.append(f"   🔗 {article['url']}")
        lines.append("")
        lines.append(f"   💡 {article['summary']}")
        lines.append("")
        lines.append("-" * 60)
        lines.append("")

    lines.append("Generated by News Summarizer Bot 🤖")
    return "\n".join(lines)


def save_digest(content: str, category: str = "technology") -> Path:
    """
    Save the digest to a text file in the output/ folder.

    Args:
        content: Formatted digest string
        category: Used in the filename

    Returns:
        Path to the saved file
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = OUTPUT_DIR / f"digest_{category}_{date_str}.txt"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    return filename